# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170103_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major',
            field=models.CharField(max_length=45),
        ),
    ]
