# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170103_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Major')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='major',
        ),
    ]
