# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_resource_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='major',
            new_name='majorc',
        ),
    ]
