# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170103_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='majorc',
            new_name='major',
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
