# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_resource_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.CharField(default=None, max_length=100, verbose_name=()),
        ),
    ]
