# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170103_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='course',
            new_name='courses',
        ),
    ]
