# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170104_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourcetype',
            field=models.CharField(choices=[('summary', 'Summary'), ('exam', 'Exam')], default='summary', max_length=45),
        ),
    ]
