# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170104_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourcetype',
            field=models.CharField(choices=[('Summary', 'Summary'), ('Exam', 'Exam')], default='summary', max_length=45),
        ),
    ]
