# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170108_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='name', chained_model_field='major', on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
