# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20170108_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='name',
            new_name='major',
        ),
    ]
