# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20170108_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['course']},
        ),
    ]
